### PR TITLE
Logic to hardcode the RPC nav link

### PR DESCRIPTION
**Pull request by andynog**
Implemented logic to show a `RPC` link in the left navigation that is not based on pages front mater but hard coded logic in `_includes\nav.html`

### CODE REVIEW

**Review by thanethomson — COMMENTED** [review]
Two things here:
1. This renders the "RPC" link at the bottom of the nav with a triangle to its left, implying there are sub-links, which isn't true. Please check the styling here.
2. When building the v0.37.0-rc2 docs, I see two "RPC" links at the bottom now. One pointing to the v0.37 OpenAPI docs, and the other pointing to the v0.34 OpenAPI docs.

**Comment by andynog** [comment]
> Two things here:
> 
>     1. This renders the "RPC" link at the bottom of the nav with a triangle to its left, implying there are sub-links, which isn't true. Please check the styling here.

Thanks @thanethomson, OK, I'll look into removing that.

> 
>     2. When building the v0.37.0-rc2 docs, I see two "RPC" links at the bottom now. One pointing to the v0.37 OpenAPI docs, and the other pointing to the v0.34 OpenAPI docs.

Did you test the it before the changes were ported to v0.37.x ? If the page was removed it shouldn't show up. But I will look into this too.

**Comment by andynog** [comment]
@thanethomson I believe I've fixed both issues reported above. The triangle on the left was removed with commit 0ac2a33 and the duplicate `RPC` link is removed with https://github.com/cometbft/cometbft/pull/420

**Review by thanethomson — APPROVED** [review]
Perfect, seems to work now. Thanks @andynog and @aaronmw!

**Pull request merged**
